services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: superbodega-db
    environment:
      SA_PASSWORD: "SuperBodega2024!"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: superbodega-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

volumes:
  sqlserver_data: